apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: maeghan-website
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: maeghan-website
        image: olivierbeaulieu/maeghan-website:latest
        ports:
        - containerPort: 90
        - containerPort: 91